name: capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - colorama
  - fuzzywuzzy
  - joblib
  - jupyter_contrib_nbextensions
  - isort
  - langdetect
  - lxml
  - lz4
  - matplotlib
  - nb_black
  - nltk
  - notebook
  - nb_conda_kernels
  - numpy
  - pandas
  - pillow
  - pip
  - pyarrow
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - streamlit
  - tqdm
  - wordcloud
  - pip:
    - amzsear
